// <auto-generated />
using System;
using MagicVilla.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla.API.Migrations
{
    [DbContext(typeof(MagicVillaContext))]
    [Migration("20230706215219_Seed")]
    partial class Seed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.API.Models.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comodidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalhes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosQuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupacao")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.Property<string>("UrlDaImagem")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vilas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comodidade = "Ar condicionado, TV, Frigobar, Cama King Size, Banheira de Hidromassagem",
                            DataAtualizacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9702),
                            DataCriacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9692),
                            Detalhes = "Vila com vista para a piscina",
                            MetrosQuadrados = 100,
                            Nome = "Vista da Piscina",
                            Ocupacao = 2,
                            Tarifa = 1000.0,
                            UrlDaImagem = "https://dotnetmastery.com/bluevillaimages/villa1.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Comodidade = "Ar condicionado, TV, Frigobar, Cama King Size, Banheira de Hidromassagem",
                            DataAtualizacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9705),
                            DataCriacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9705),
                            Detalhes = "Vila com vista para o lago",
                            MetrosQuadrados = 200,
                            Nome = "Vista do Lago",
                            Ocupacao = 4,
                            Tarifa = 2000.0,
                            UrlDaImagem = "https://dotnetmastery.com/bluevillaimages/villa2.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Comodidade = "Ar condicionado, TV, Frigobar, Cama King Size, Banheira de Hidromassagem",
                            DataAtualizacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9707),
                            DataCriacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9707),
                            Detalhes = "Vila com vista para o mar",
                            MetrosQuadrados = 300,
                            Nome = "Vista do Mar",
                            Ocupacao = 6,
                            Tarifa = 3000.0,
                            UrlDaImagem = "https://dotnetmastery.com/bluevillaimages/villa3.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Comodidade = "Ar condicionado, TV, Frigobar, Cama King Size, Banheira de Hidromassagem",
                            DataAtualizacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9709),
                            DataCriacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9709),
                            Detalhes = "Vila com vista para o jardim",
                            MetrosQuadrados = 400,
                            Nome = "Vista do Jardim",
                            Ocupacao = 8,
                            Tarifa = 4000.0,
                            UrlDaImagem = "https://dotnetmastery.com/bluevillaimages/villa4.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Comodidade = "Ar condicionado, TV, Frigobar, Cama King Size, Banheira de Hidromassagem",
                            DataAtualizacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9711),
                            DataCriacao = new DateTime(2023, 7, 6, 18, 52, 19, 167, DateTimeKind.Local).AddTicks(9711),
                            Detalhes = "Vila com vista para a montanha",
                            MetrosQuadrados = 500,
                            Nome = "Vista da Montanha",
                            Ocupacao = 10,
                            Tarifa = 5000.0,
                            UrlDaImagem = "https://dotnetmastery.com/bluevillaimages/villa5.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
